### ISSUE TITLE
Support opening email directly from Windows 10 notification

### ISSUE THREAD

**Issue by andrew-dc** [Thomas101/wmail#239] opened 2016-08-08 03:39 UTC
It'd be great to have to click the Windows 10 notification for an email and go directly to the email, rather than just open Wmail up.

**Comment by aoberoi** [comment] 2016-08-24 13:13
I'd like to add that this isn't just true for Windows 10 notifications. I'd like the same behavior for OS X notifications too.

**Comment by Thomas101** [comment] 2016-08-24 19:23
Something I've not quite got around to yet. This is a duplicate of #171. I'm going to close this one up, but you can continue tracking it from there. Thanks!

**Closed by Thomas101** 2016-08-24 19:23 UTC
