### ISSUE TITLE
taskbar

### ISSUE THREAD

**Issue by sakshamgoyal01** [Thomas101/wmail#258] opened 2016-08-24 15:38 UTC
What the hell is this?
![image](https://cloud.githubusercontent.com/assets/19929553/17937151/611b7b60-6a4b-11e6-9986-7f6eed93a5c3.png)

V 1.6.3
windows 10

**Comment by Thomas101** [comment] 2016-08-24 16:36
Duplicate of #220

**Closed by Thomas101** 2016-08-24 16:36 UTC
Labels: duplicate
