### ISSUE TITLE
Preferences shortcut stops working on OSX

### ISSUE THREAD

**Issue by slashjs** [Thomas101/wmail#301] opened 2016-09-09 12:00 UTC
The shortcut for preferences `⌘ + ,` stops working. It initially works upon startup of WMail, but then stops working after using the application.

Preferences are still accessible from the WMail menu bar dropdown.

**WMail** 1.3.1
**Mac OSX El Capitan** 10.11.6

**Comment by Thomas101** [comment] 2016-09-10 07:41
Hi, have you tried using the latest pre-release? I think this has been resolved.

**Comment by slashjs** [comment] 2016-09-10 12:22
Hello, I've just upgraded to the latest pre-release (`1.3.8`) and I'm still able to reproduce this issue. In fact the shortcut isn't working at all for me anymore.

**Comment by Thomas101** [comment] 2016-09-10 12:35
Thanks. It's stopped working between 1.3.7 and 1.3.8. Looks like an issue with electron. https://github.com/electron/electron/issues/7170

**Comment by slashjs** [comment] 2016-09-10 12:42
No problem. I've actually managed to get the shortcut working but the steps to reproduce are a little weird.

1. Switch mailbox with `⌘ + 1` or `⌘ + 2`
2. Don't let go of `⌘`
3. Press `,`
4. Tada 🎉

Not sure if that helps if it's a problem with Electron, but I thought I would let you know. 👍

**Comment by Thomas101** [comment] 2016-09-10 12:44
Thanks. I'll pass this through to the electron team 👍

**Comment by Thomas101** [comment] 2016-09-13 16:20
I'm struggling to make this happen in a reliable way. Are you still having trouble with it? Have you managed to find anything that always makes it trigger on and off?

**Comment by slashjs** [comment] 2016-09-14 08:21
I'm still having the same issue, the only time I can get the shortcut to work is by pressing a different shortcut beforehand, for example; `⌘ + f`.

It might be worth noting that after pressing `⌘ + f`, you can let go of `⌘` and then press `⌘ + ,` and it works. But in other cases such as `⌘ + 1` you need to continuously hold `⌘` before pressing `,` otherwise it won't work.

If that makes sense?

**Comment by Thomas101** [comment] 2016-09-14 18:05
Yeah thats what I saw but it seemed to magically fix itself :-(. If you hold cmd and keep pressing comma does that eventually work?

**Comment by slashjs** [comment] 2016-09-14 20:50
Hmm, if mine does the same I'll keep an eye out to see what could have triggered it.

> If you hold cmd and keep pressing comma does that eventually work?

Nope :/

**Comment by Thomas101** [comment] 2016-09-18 20:47
I've just updated to the latest electron which also updates to the latest version of chrome. When I've been testing it seems to bring up the settings every time so I'll close this off for now, but feel free to re-open when the release comes out if you still see the issue. Thanks!

**Comment by slashjs** [comment] 2016-09-21 14:13
I've just upgraded to the latest pre-release (`1.3.9`) and unfortunately I'm still having this issue.

**Comment by Thomas101** [comment] 2016-10-05 19:37
Hi do you still see this in the [1.4.0 prerelease](https://github.com/Thomas101/wmail/releases/tag/v1.4.0)?

**Comment by slashjs** [comment] 2016-10-06 16:12
Hello, yes I'm still seeing it.

**Comment by Thomas101** [comment] 2016-10-06 19:42
When you press `cmd+,` do you see `WMail` highlight briefly in the menu bar?

**Comment by slashjs** [comment] 2016-10-07 15:15
Nope, I don't see that when cheating the shortcut either though. (by using other shortcuts before, as discussed previously)

**Comment by Thomas101** [comment] 2016-10-29 10:05
Hi I've been looking more into this and I'm having real trouble reproducing it reliably. Having said that I have seen it, so it's definitely there. I've triple checked the WMail code and there's nothing untoward in there so I can only think that it's an upstream bug either with electron or chrome.

I did raise an issue with electron but without a reliable way to reproduce it they're in the same boat as me chasing tails. As you're still able to toggle the settings by other means (point & click or the settings button in the main window) I'm going to close this off as upstream and wontfix otherwise I'm going to continue bouncing this between milestones with no clear way to fix it.

Thanks for reporting though - wish I could have narrowed this down a bit more though!

**Closed by Thomas101** 2016-10-29 10:05 UTC
Labels: bug, osx
