### ISSUE TITLE
Composing email message in a new window does not work

### ISSUE THREAD

**Issue by rajprins** [Thomas101/wmail#560] opened 2017-02-01 21:15 UTC
**Description**
Composing a new message by either pressing shift-C or holding the shift key while clicking "compose" does not launch a new window; in fact, nothing happens.

**Details**
* Version: 2.0.9 pre-release
* Operating System: macOS Sierrra

**Comment by Thomas101** [comment] 2017-02-03 08:28
Hi thanks for reporting. This is a duplicate of #363 you can continue tracking progress from there. Thanks!

**Closed by Thomas101** 2017-02-03 08:28 UTC
