### ISSUE TITLE
Logged out of GAE

### ISSUE THREAD

**Issue by domoritz** [Thomas101/wmail#134] opened 2016-03-18 06:42 UTC
Every time I restart wmail, I get logged out of my google apps for education accounts (gmail). My friends reported similar issues.

**Comment by BrandonSmith** [comment] 2016-04-01 02:06
I, too, get logged out each time I restart. My account is also a Google Apps for Work through my employer. It is likely they have some type of token policy in place.

I have another Google Apps for Work as a personal account (free) which does NOT get logged out.

**Comment by domoritz** [comment] 2016-04-01 04:53
Any idea how we can debug/ fix this? I doubt that I can change how my University wired app Google Apps.

**Comment by vitorgalvao** [comment] 2016-04-26 05:06
I also have a Google Apps account that is logged out occasionally. Not on every restart, though, just some times.

**Comment by Thomas101** [comment] 2016-04-26 07:31
I've been testing with a google apps account and see the same as @vitorgalvao. It must be something to do with cookie validity being shorter on apps accounts. I'll look to see if there's a way to extend the validity of the cookie by using the oauth token that's used for notifications

**Comment by domoritz** [comment] 2016-05-13 07:28
What's super weird is that the notification count seems to be correct even when I got seemingly logged out.

**Comment by Thomas101** [comment] 2016-05-13 07:31
@domoritz that's because when you sign in google places a cookie in the app which is used for validating your display of inbox/gmail (this is the one that expires). During the sign in process the app also escalates the cookie to get an api key that it can consistently re-visit and this is what's used for grabbing unread counts & notifications

**Comment by domoritz** [comment] 2016-05-17 03:29
So does wmail not persist the cookies beyond a restart of the app? It seems like it persists cookies for gmail but not my university.

**Comment by Thomas101** [comment] 2016-05-17 07:49
It does persist them, but by the looks of it google is more stringent about the length of time they are persisted & valid for. I'm guessing that this is something that can be set by the network admin as some accounts persist for a week or so, whereas others seem to be much shorter. I need to investigate if I can use the permanent access token that's used for unread calls to authenticate a browser client. A quick google hasn't revealed anything but there must be a way to do it!

**Comment by domoritz** [comment] 2016-05-17 21:57
What's odd is that the cookie in chrome persists beyond a restart but in wmail I have to log in every time I restart the app. Is there something I can give you to help you debug?

**Comment by Thomas101** [comment] 2016-06-05 16:21
I've had any idea, could you give this a try....

1.) Open Wmail and go to View > Developer Tools & click on the console tab
2.) Paste the following code into the text area... (this assumes the account that gets logged out is top of the list. If it's not increase `index` accordingly.
```js
const index = 0
const mailbox = JSON.parse(window.localStorage.Mailbox_index)[index]
const ipc = window.nativeRequire('electron').ipcRenderer
ipc.send('new-window', { partition: 'persist:' + mailbox, url: 'https://accounts.google.com/logout' })
```
3.) The window that's popped up will redirect a few times but eventually take you to a sign in page. Don't enter your password here, instead click on `sign in with different account`
4.) On this page enter the same email address that you original signed up with (I know we said to sign in with a different account, but we're not) and press sign in
5.) On the next page you'll be prompted for your password. Enter it, but before pressing sign in make sure that the `Stay Signed in` box is checked.
6.) You'll now be directed to your google accounts page. You can close this window.
7.) Back in the main Wmail window, go to `View>Reload`.

Does that keep you signed in now?

**Comment by vitorgalvao** [comment] 2016-06-05 16:35
Couldn’t do it with `const`
![](https://i.imgur.com/Oiz0eAU.png)

Did it with `var` instead.

It’s done, but since [I only get logged out occasionally](https://github.com/Thomas101/wmail/issues/134#issuecomment-214617578), will take a while to know if it worked.

**Comment by Thomas101** [comment] 2016-06-05 17:55
Great! Keep me posted!

**Comment by domoritz** [comment] 2016-06-05 19:36
I followed the steps but after step 1) and 2) I don't get a window where I can sign in with a different account. 

![screen shot 2016-06-05 at 21 34 17](https://cloud.githubusercontent.com/assets/589034/15807721/599d2372-2b65-11e6-9b60-c7e4675d8eaf.png)

Even closing the window and logging in in the main WMail window does not help.

Also, at step 7), I don't get logged out when I reload but only if I close and open WMail. 

Thanks for looking into this!

**Comment by Thomas101** [comment] 2016-06-05 19:44
Ah, now that's interesting. It looks like your sysadmin has put a time constraint on how long you can be logged in. If you log into inbox in your web browser how long is it until you have to login again?

**Comment by domoritz** [comment] 2016-06-05 19:46
Yes, that is correct. I don't know exactly but maybe once a week I have to log back into gmail/calendar (education accounts don't support google inbox yet). However, in Chrome/Firefox/Safari I don't get logged out of my gae account/ gmail if I restart the browser.

**Comment by vitorgalvao** [comment] 2016-06-19 16:52
I was just logged out, so it did not work.

**Comment by Thomas101** [comment] 2016-06-30 18:24
I've just had the same issue on a fresh install my end. Did you open the `New sign-in from Chrome on Mac` email when you signed in the first time? I noticed it kept logging me out until I opened that message or marked it as read then it started working as expected after that.

If you want to re-trigger the e-mail, I think you should be able to by deleting `~/Library/Application Support/wmail/`

**Comment by domoritz** [comment] 2016-06-30 22:52
I never got this email but tried to delete `~/Library/Application Support/wmail/` and add all accounts again. Again, I get logged out when I close wmail. In chrome/Firefox I don't get log out by a restart.

**Comment by Thomas101** [comment] 2016-09-08 20:04
Going to close this as I don't seem to be able to reproduce it and it looks might be set by the network admin on google apps for work etc

**Comment by domoritz** [comment] 2016-09-08 20:18
Hmm. Too bad. I I'm still having the same issue and would be surprised if it was set by the network admin since it works fine in Chrome/Firefox or any other browser. Thanks for all the debugging effort so far. 

@Thomas101 Are there any restrictions on the domains for which you store cookies or sessions?

**Comment by Thomas101** [comment] 2016-09-08 20:29
No, should be right across the board! On a technical level it's the same as having a new browser window in chrome. I'm completely stumped as to why it's not working. All the more difficult that I can't reproduce it too :-(

**Comment by Thomas101** [comment] 2016-09-08 20:42
@domoritz it's probably not possible but do you think the university would be able to supply an account I could use for testing?

**Comment by domoritz** [comment] 2016-09-08 23:03
@Thomas101 I sent you something though the contact form.

**Closed** 2016-09-19 18:17 UTC
Labels: bug, investigate

**Comment by domoritz** [comment] 2016-09-19 18:21
🎉

**Comment by Thomas101** [comment] 2016-09-20 17:05
Thanks to logs of debugging from @domoritz I think this is now fixed! It's been added to the latest [prerelease](https://github.com/Thomas101/wmail/releases). Once you've added your account go to `settings` then click on the `account` tab. Pick your account and toggle the `Artificially Persist Cookies` option to be on. Next time you launch WMail you should (*fingers crossed*) still be signed in!

**Comment by chadberg** [comment] 2016-09-21 16:30
This solves the issue with me as well. GAE with Shibboleth. Thanks @Thomas101 and @domoritz
