### ISSUE TITLE
Spell check in other languages.

### ISSUE THREAD

**Issue by sicofante** [Thomas101/wmail#232] opened 2016-08-01 23:30 UTC
Allow spell checking to be performed in other languages than English.

It should be fairly easy to add the languages since it's a Chromium feature.

Maybe this is an internationalization and localization dept. issue, but remember Chromium supports several languages SIMULTANEOUSLY, and most bilingual speakers need the simultaneous support that's characteristic to Chromium.

**Comment by Thomas101** [comment] 2016-08-02 17:52
Hi, this is a duplicate of #139. You can track progress there

**Closed by Thomas101** 2016-08-02 17:52 UTC
