### ISSUE TITLE
Feature Request Linux: Clicking the unread mail in the system tray area opens wmail 

### ISSUE THREAD

**Issue by Feichtmeier** [Thomas101/wmail#213] opened 2016-07-23 10:31 UTC
Hi and thanks for your application!
Would it be possible to open the wmail main window after clicking the line in the tray area which shows the title of the unread message?

Thanks in advance!

**Comment by Thomas101** [comment] 2016-08-02 17:57
Duplicate of #171. You can track progress from there

**Closed by Thomas101** 2016-08-02 17:57 UTC
