### ISSUE TITLE
default mailer on OSX

### ISSUE THREAD

**Issue by aldonz** [Thomas101/wmail#158] opened 2016-05-09 13:14 UTC
Would like to make Wmail the default mail client on Mac OSX, but it will not stick when I change the setting in Mac Mail preferences. Also, when I click an email link in Firefox, no new message in created in Wmail (I have changed the mailto setting in Firefox Applications preferences to "Use Wmail"). Is there any way these default mail settings can be fixed...or, if implemented already, can detailed instructions be posted to show how it is done.

**Comment by Thomas101** [comment] 2016-05-09 19:18
Duplicate of #66. Need to get a move on and get this added though!

**Closed by Thomas101** 2016-05-09 19:18 UTC
Labels: duplicate
