### ISSUE TITLE
Opening email from menubar (UX)

### ISSUE THREAD

**Issue by webchun** [Thomas101/wmail#390] opened 2016-10-25 04:02 UTC
* Which version of WMail are you using? [e.g. 1.3.1]
2.0.1 Pre release
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Mac Os Sierra

When I click on any email item from the menu bar it will open up Wmail App with associated email account tab opened. Is it possible to trigger it open the associated email directly in the WMail?

**Comment by Thomas101** [comment] 2016-10-26 11:18
duplicate of #171

**Closed by Thomas101** 2016-10-26 11:18 UTC
