### ISSUE TITLE
Clicking on an email address does not trigger "Compose" window

### ISSUE THREAD

**Issue by iRomain** [Thomas101/wmail#192] opened 2016-07-01 08:52 UTC
I am now using WMail as my default mail client (Apple Mail > Preferences > Default email reader)
However, when I click on an email link anywhere in my system it opens WMail or brings it to the front if already open but it won't do anything else.
Expected behaviour would be to open the compose window.

**Comment by Thomas101** [comment] 2016-07-06 21:00
duplicate of #66

**Closed by Thomas101** 2016-07-06 21:00 UTC
Labels: duplicate
