### ISSUE TITLE
125% DPI support (Windows 10)

### ISSUE THREAD

**Issue by saifulwebid** [Thomas101/wmail#227] opened 2016-07-28 11:41 UTC
I'm using Windows 10 with Full HD resolution and 125% zoom level in Windows DPI setting set. But Wmail doesn't respect this setting; it's displaying Gmail with 100% DPI setting, making it looks smaller.

I noticed that Wmail maybe using Chrome under the hood, and noticed this recently-fixed bug in Chrome when using 125% DPI: https://bugs.chromium.org/p/chromium/issues/detail?id=410696

**Comment by jonohill** [comment] 2016-07-30 00:04
Try `Ctrl+plus` as a workaround. I found it didn't work with the numeric keypad `+` so it's really `Ctrl+Shift+=`
Wmail will remember your zoom level if you quit and relaunch as well.

**Comment by Thomas101** [comment] 2016-08-02 17:50
Duplicate of #221. You can keep up to date with progress there

**Closed by Thomas101** 2016-08-02 17:50 UTC
