### ISSUE TITLE
Badge icon not updating unread count [OSX]

### ISSUE THREAD

**Issue by postrational** [Thomas101/wmail#182] opened 2016-06-07 08:22 UTC
Hi there, I'm using Wmail and think it's really cool. Thanks for making it.

I'm having an issue with the unread count badge on the sidebar icons and on the application icon. 
At one point they got stuck at a certain value and they never change.

At first I noticed that these numbers stopped updating (perhaps after an upgrade to version 1.2.1).
I upgraded to version 1.3.1, the badge counts remained stuck at the old values.

I removed all caches, preferences and other files related to Wmail and set it up again.
Now I simply have no count badges at all.

I looked into the dev tools console logs and noticed the following messages appear repeatedly:

    [SYNC ERR] Mailbox Unread Messages 
    err: Error: Missing required parameters: userId
        at createAPIRequest (/Applications/WMail.app/Contents/Resources/app/node_modules/googleapis/lib/apirequest.js:110:14)
        at Object.Gmail.self.users.messages.list (/Applications/WMail.app/Contents/Resources/app/node_modules/googleapis/apis/gmail/v1.js:728:16)
        at file:///Applications/WMail.app/Contents/Resources/app/bin/mailbox.js:44:7370
        at e.r.value (file:///Applications/WMail.app/Contents/Resources/app/bin/mailbox.js:44:7327)
        at file:///Applications/WMail.app/Contents/Resources/app/bin/mailbox.js:36:8582__proto__: Object
    mailbox.js:36 

    [SYNC ERR] Mailbox Unread Messages 
    err: Error: Missing required parameters: userId
        at createAPIRequest (/Applications/WMail.app/Contents/Resources/app/node_modules/googleapis/lib/apirequest.js:110:14)
        at Object.Gmail.self.users.messages.list (/Applications/WMail.app/Contents/Resources/app/node_modules/googleapis/apis/gmail/v1.js:728:16)
        at file:///Applications/WMail.app/Contents/Resources/app/bin/mailbox.js:44:7370
        at e.r.value (file:///Applications/WMail.app/Contents/Resources/app/bin/mailbox.js:44:7327)
        at file:///Applications/WMail.app/Contents/Resources/app/bin/mailbox.js:36:8582__proto__: Object
    mailbox.js:36 

    [SYNC ERR] Mailbox Unread Count 
    err: Error: Missing required parameters: userId
        at createAPIRequest (/Applications/WMail.app/Contents…}err: Error: Missing required parameters: userId
        at createAPIRequest (/Applications/WMail.app/Contents/Resources/app/node_modules/googleapis/lib/apirequest.js:110:14)
        at Object.Gmail.self.users.labels.get (/Applications/WMail.app/Contents/Resources/app/node_modules/googleapis/apis/gmail/v1.js:443:16)
        at file:///Applications/WMail.app/Contents/Resources/app/bin/mailbox.js:44:7130
        at e.r.value (file:///Applications/WMail.app/Contents/Resources/app/bin/mailbox.js:44:7089)
        at Object.r.value (file:///Applications/WMail.app/Contents/Resources/app/bin/mailbox.js:36:7177)
        at Object.c [as syncMailboxUnreadCount] (file:///Applications/WMail.app/Contents/Resources/app/bin/mailbox.js:43:16256)
        at webview.<anonymous> (file:///Applications/WMail.app/Contents/Resources/app/bin/mailbox.js:44:20003)
        at WebViewImpl.dispatchEvent (/Applications/WMail.app/Contents/Resources/electron.asar/renderer/web-view/web-view.js:182:29)
        at EventEmitter.<anonymous> (/Applications/WMail.app/Contents/Resources/electron.asar/renderer/web-view/guest-view-internal.js:72:22)
        at emitTwo (events.js:100:13)
        at EventEmitter.emit (events.js:185:7)__proto__: Object

It would be great if you could take a look at this.

BTW: I don't know if this is related, but I'm behind a corporate proxy server.

**Comment by Thomas101** [comment] 2016-06-08 07:41
Hi, by the looks of the error it's failed to sync your account profile, which means it won't have got your email address, which in turn means that when it's calling out to get the unread counts it's missing `userId` (which is actually your email).

The proxy is the most probable cause here. If you got settings then advanced have you added any proxy server details here?

**Comment by gkapatai** [comment] 2016-06-22 10:18
I get the same problem
```
"Error: Missing required parameters: userId at createAPIRequest (/Applications/WMail.app/Contents/Resources/app/node_modules/googleapis/lib/apirequest.js:110:14) at Object.Gmail.self.users.labels.get 
(/Applications/WMail.app/Contents/Resources/app/node_modules/googleapis/apis/gmail/v1.js:443:16) at file:///Applications/WMail.app/Contents/Resources/app/bin/mailbox.js:44:7130 at e.r.value 
(file:///Applications/WMail.app/Contents/Resources/app/bin/mailbox.js:44:7089) at Object.r.value 
(file:///Applications/WMail.app/Contents/Resources/app/bin/mailbox.js:36:7177) at Object.c [as syncMailboxUnreadCount] 
(file:///Applications/WMail.app/Contents/Resources/app/bin/mailbox.js:43:16256) at 
file:///Applications/WMail.app/Contents/Resources/app/bin/mailbox.js:36:6757 at Array.map (native) at 
Object.r.value (file:///Applications/WMail.app/Contents/Resources/app/bin/mailbox.js:36:6732) at Object.c [as syncAllMailboxUnreadCounts] 
(file:///Applications/WMail.app/Contents/Resources/app/bin/mailbox.js:43:16256)
"
```

I am also behind a proxy and have set this in advanced. It's working fine for receiving/sending email.

**Comment by bitbrained** [comment] 2016-06-23 15:56
I've experience the same issue, but possible due to a different root cause. I've observed these messages in the 
```
[SYNC ERR] Mailbox Unread Messages DOMException: Failed to set the 'Mailbox_XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX' property on 'Storage': Setting the value of 'Mailbox_XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX' exceeded the quota.
    at Error (native)
    at Object.e.exports.set (file:///Applications/WMail.app/Contents/Resources/app/bin/mailbox.js:36:21260)
    at t.r.value (file:///Applications/WMail.app/Contents/Resources/app/bin/mailbox.js:36:14352)
    at t.r.value (file:///Applications/WMail.app/Contents/Resources/app/bin/mailbox.js:36:16529)
    at file:///Applications/WMail.app/Contents/Resources/app/bin/mailbox.js:43:24204
    at Array.every (native)
    at file:///Applications/WMail.app/Contents/Resources/app/bin/mailbox.js:43:24177
    at p (file:///Applications/WMail.app/Contents/Resources/app/bin/mailbox.js:43:23803)
    at Object.ID_1 (file:///Applications/WMail.app/Contents/Resources/app/bin/mailbox.js:43:24139)
    at e._invokeCallback (file:///Applications/WMail.app/Contents/Resources/app/bin/mailbox.js:50:25962)
```

**Comment by Thomas101** [comment] 2016-07-06 20:56
Do you still experience this with the latest [pre-release](https://github.com/Thomas101/wmail/releases/tag/1.3.2)?

**Comment by bitbrained** [comment] 2016-07-06 23:55
@Thomas101, no, I don't observe the error messages in the [1.3.2 pre-release](https://github.com/Thomas101/wmail/releases/tag/1.3.2).

**Comment by Thomas101** [comment] 2016-07-07 05:13
Excellent! I'll close this issue :-)

**Closed by Thomas101** 2016-07-07 05:13 UTC

**Comment by postrational** [comment] 2016-07-07 09:13
Unfortunately, I am still seeing the issue in 1.3.2 prerelease

**Comment by locly** [comment] 2016-07-07 11:28
Hi @postrational by the looks of the error, the request is timing out. Have you entered the proxy server settings in `settings > advanced`? Do you have any information about the proxy server your sat behind?

**Comment by Thomas101** [comment] 2016-07-07 11:29
Hi @postrational by the looks of the error, the request is timing out. Have you entered the proxy server settings in `settings > advanced`? Do you have any information about the proxy server your sat behind?

**Comment by postrational** [comment] 2016-07-08 09:15
What information about the proxy could I provide?

**Comment by Thomas101** [comment] 2016-07-09 09:42
Sorry I just wanted to check that you've setup the proxy settings under `settings > advanced` first as the browser window has to use a separate method to connect from the sync calls and unfortunately there's no automatic way to grab these settings.
