### ISSUE TITLE
Request: bring up preferences pane with OS-standard keyboad shortcut

### ISSUE THREAD

**Issue by lid** [Thomas101/wmail#97] opened 2016-02-11 18:41 UTC
This should be an easy one - provide a menu item and OS-relevant keyboard shortcut to bring up the preferences pane. On Mac OS X, this is `⌘-,`.

**Comment by Thomas101** [comment] 2016-02-20 08:36
Duplicate of #100 added :)

**Closed by Thomas101** 2016-02-20 08:36 UTC

**Comment by Thomas101** [comment] 2016-02-20 17:43
Hello! I've added this into the latest pre-release (1.2.1) which is available on the [downloads page](http://thomas101.github.io/wmail/download) or from the [direct link](https://github.com/Thomas101/wmail/releases/download/v1.2.1/WMail_1_2_1_osx_prerelease.zip). 

Thanks for your help!
