### ISSUE TITLE
Window content moved to the left (Windows 10)

### ISSUE THREAD

**Issue by aziascreations** [Thomas101/wmail#228] opened 2016-07-30 23:29 UTC
I've been using the app and suddenly, after adding an account if I remember correctly, the whle content of the window is "shifted" to the left and offscreen.

I've tried resizing it and rebooting the computer, but nothing helps.

Screenshot: [Imgur](http://i.imgur.com/C0wYKAx.png)

**Comment by SmogMonkey** [comment] 2016-08-02 00:55
Same thing OSX El Capitan 10.11.5, WMail 1.3.5 pre-release, closing and re-opening resets view to normal. I believe it happened after switching from an account that just went to 'Inbox Zero' to an account with messages.
![image](https://cloud.githubusercontent.com/assets/2555178/17313513/50f00e6e-582a-11e6-8439-2cc6234ca844.png)

**Comment by Thomas101** [comment] 2016-08-02 17:51
Duplicate of #211. You can track progress there

**Closed by Thomas101** 2016-08-02 17:51 UTC
